package com.example.meal_prep_app

// hardcoded meal list used for the Room insert task
// these are added when the user presses the add meals button
object HardcodedMeals {

    fun getMeals(): List<Meal> {
        return listOf(
            Meal(
                mealName = "Sweet and Sour Pork",
                drinkAlternate = "",
                category = "Pork",
                area = "Chinese",
                instructions = "Preparation\n1. Crack the egg into a bowl. Separate the egg white and yolk.\n2. Slice the pork tenderloin into strips.\n3. Prepare the marinade using a pinch of salt, one teaspoon of starch, two teaspoons of light soy sauce, and an egg white.\n4. Marinade the pork strips for about 20 minutes.\n5. Put the remaining starch in a bowl. Add some water and vinegar to make a starchy sauce.\nCooking Instructions\n1. Pour the cooking oil into a wok and heat to 190C. Add the marinated pork strips and fry them until they turn brown.\n2. Leave some oil in the wok. Put the tomato sauce and white sugar into the wok.\n3. Add some water to the wok and thoroughly heat the sweet and sour sauce before adding the pork strips.\n4. Pour in the starchy sauce. Stir-fry all the ingredients until the pork and sauce are thoroughly mixed.\n5. Serve on a plate and add some coriander for decoration.",
                mealThumb = "https://www.themealdb.com/images/media/meals/1529442316.jpg",
                tags = "Sweet",
                youtube = "https://www.youtube.com/watch?v=mdaBIhgEAMo",
                ingredient1 = "Pork", ingredient2 = "Egg", ingredient3 = "Water",
                ingredient4 = "Salt", ingredient5 = "Sugar", ingredient6 = "Soy Sauce",
                ingredient7 = "Starch", ingredient8 = "Tomato Puree", ingredient9 = "Vinegar",
                ingredient10 = "Coriander", ingredient11 = "", ingredient12 = "",
                ingredient13 = "", ingredient14 = "", ingredient15 = "",
                ingredient16 = "", ingredient17 = "", ingredient18 = "",
                ingredient19 = "", ingredient20 = "",
                measure1 = "200g", measure2 = "1", measure3 = "Dash",
                measure4 = "1/2 tsp", measure5 = "1 tsp", measure6 = "10g",
                measure7 = "10g", measure8 = "30g", measure9 = "10g",
                measure10 = "Dash", measure11 = "", measure12 = "",
                measure13 = "", measure14 = "", measure15 = "",
                measure16 = "", measure17 = "", measure18 = "",
                measure19 = "", measure20 = ""
            ),
            Meal(
                mealName = "Chicken Marengo",
                drinkAlternate = "",
                category = "Chicken",
                area = "French",
                instructions = "Heat the oil in a large flameproof casserole dish and stir-fry the mushrooms until they start to soften. Add the chicken legs and cook briefly on each side to colour them a little.\nPour in the passata, crumble in the stock cube and stir in the olives. Season with black pepper. Cover and simmer for 40 mins until the chicken is tender. Sprinkle with parsley and serve with pasta and a salad, or mash and green veg, if you like.",
                mealThumb = "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
                tags = "",
                youtube = "https://www.youtube.com/watch?v=U33HYUr-0Fw",
                ingredient1 = "Olive Oil", ingredient2 = "Mushrooms", ingredient3 = "Chicken Legs",
                ingredient4 = "Passata", ingredient5 = "Chicken Stock Cube", ingredient6 = "Black Olives",
                ingredient7 = "Parsley", ingredient8 = "", ingredient9 = "",
                ingredient10 = "", ingredient11 = "", ingredient12 = "",
                ingredient13 = "", ingredient14 = "", ingredient15 = "",
                ingredient16 = "", ingredient17 = "", ingredient18 = "",
                ingredient19 = "", ingredient20 = "",
                measure1 = "1 tbs", measure2 = "300g", measure3 = "4",
                measure4 = "500g", measure5 = "1", measure6 = "100g",
                measure7 = "Chopped", measure8 = "", measure9 = "",
                measure10 = "", measure11 = "", measure12 = "",
                measure13 = "", measure14 = "", measure15 = "",
                measure16 = "", measure17 = "", measure18 = "",
                measure19 = "", measure20 = ""
            ),
            Meal(
                mealName = "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
                drinkAlternate = "",
                category = "Beef",
                area = "Vietnamese",
                instructions = "1. Place rice in a fine-mesh sieve and rinse until water runs clear. Add to a small pot with 1 cup water and a pinch of salt. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15 minutes.\n2. Wash and dry all produce. Peel and finely chop garlic. Zest and quarter lime. Trim and halve cucumber lengthwise; thinly slice crosswise. Halve, peel, and medium dice onion. Trim, peel, and grate carrot.\n3. Combine cucumber, juice from half the lime, 1/4 tsp sugar, and a pinch of salt. Combine mayonnaise, a pinch of garlic, a squeeze of lime juice, and sriracha. Season with salt and pepper.\n4. Heat oil in a large pan over medium-high heat. Add onion and cook until softened, 4-5 minutes. Add beef, remaining garlic, and 2 tsp sugar. Cook until beef is browned, 4-5 minutes. Stir in soy sauce.\n5. Fluff rice with a fork; stir in lime zest and butter. Divide rice between bowls. Arrange beef, grated carrot, and pickled cucumber on top.",
                mealThumb = "https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg",
                tags = "",
                youtube = "",
                ingredient1 = "Rice", ingredient2 = "Onion", ingredient3 = "Lime",
                ingredient4 = "Garlic Clove", ingredient5 = "Cucumber", ingredient6 = "Carrots",
                ingredient7 = "Ground Beef", ingredient8 = "Soy Sauce", ingredient9 = "",
                ingredient10 = "", ingredient11 = "", ingredient12 = "",
                ingredient13 = "", ingredient14 = "", ingredient15 = "",
                ingredient16 = "", ingredient17 = "", ingredient18 = "",
                ingredient19 = "", ingredient20 = "",
                measure1 = "White", measure2 = "1", measure3 = "1",
                measure4 = "3", measure5 = "1", measure6 = "3 oz",
                measure7 = "1 lb", measure8 = "2 oz", measure9 = "",
                measure10 = "", measure11 = "", measure12 = "",
                measure13 = "", measure14 = "", measure15 = "",
                measure16 = "", measure17 = "", measure18 = "",
                measure19 = "", measure20 = ""
            ),
            Meal(
                mealName = "Leblebi Soup",
                drinkAlternate = "",
                category = "Vegetarian",
                area = "Tunisian",
                instructions = "Heat the oil in a large pot. Add the onion and cook until translucent.\nDrain the soaked chickpeas and add them to the pot together with the vegetable stock. Bring to the boil, then reduce the heat and cover. Simmer for 30 minutes.\nIn the meantime toast the cumin in a small ungreased frying pan, then grind them in a mortar. Add the garlic and salt and pound to a fine paste.\nAdd the paste and the harissa to the soup and simmer until the chickpeas are tender, about 30 minutes.\nSeason to taste with salt, pepper and lemon juice and serve hot.",
                mealThumb = "https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg",
                tags = "Soup",
                youtube = "https://www.youtube.com/watch?v=BgRifcCwinY",
                ingredient1 = "Olive Oil", ingredient2 = "Onion", ingredient3 = "Chickpeas",
                ingredient4 = "Vegetable Stock", ingredient5 = "Cumin", ingredient6 = "Garlic",
                ingredient7 = "Salt", ingredient8 = "Harissa Spice", ingredient9 = "Pepper",
                ingredient10 = "Lime", ingredient11 = "", ingredient12 = "",
                ingredient13 = "", ingredient14 = "", ingredient15 = "",
                ingredient16 = "", ingredient17 = "", ingredient18 = "",
                ingredient19 = "", ingredient20 = "",
                measure1 = "2 tbs", measure2 = "1 medium finely diced", measure3 = "250g",
                measure4 = "1.5L", measure5 = "1 tsp", measure6 = "5 cloves",
                measure7 = "1/2 tsp", measure8 = "1 tsp", measure9 = "Pinch",
                measure10 = "1/2", measure11 = "", measure12 = "",
                measure13 = "", measure14 = "", measure15 = "",
                measure16 = "", measure17 = "", measure18 = "",
                measure19 = "", measure20 = ""
            )
        )
    }
}